export const DOMElements = {
    connectBtn: document.getElementById('connect-btn'),
    weightInput: document.getElementById('weight-input'),
    gpxUpload: document.getElementById('gpx-upload'),
    gpxFileName: document.getElementById('gpx-file-name'),
    createRaceBtn: document.getElementById('create-race-btn'),
    bluetoothStatus: document.getElementById('bluetooth-status').querySelector('p:last-child'),
    raceStatus: document.getElementById('race-status').querySelector('p:last-child'),
    userIdDisplay: document.getElementById('user-id-display').querySelector('p:last-child'),
    powerDisplay: document.getElementById('power-display'),
    speedDisplay: document.getElementById('speed-display'),
    distanceDisplay: document.getElementById('distance-display'),
    gradientDisplay: document.getElementById('gradient-display'),
    totalDistanceDisplay: document.getElementById('total-distance-display'),
    leaderboard: document.getElementById('leaderboard'),
    courseProfileContainer: document.getElementById('course-profile-container'),
    courseProfileCanvas: document.getElementById('course-profile-canvas'),
    shareLinkSection: document.getElementById('share-link-section'),
    shareLinkInput: document.getElementById('share-link-input'),
    copyLinkBtn: document.getElementById('copy-link-btn'),
    preRaceControls: document.getElementById('pre-race-controls'),
    countdownSection: document.getElementById('countdown-section'),
    countdownTimer: document.getElementById('countdown-timer'),
    startTimerControls: document.getElementById('start-timer-controls'),
    // Debug elements
    debugPanel: document.getElementById('debug-panel'),
    debugRawHex: document.getElementById('debug-raw-hex'),
    debugParsedPower: document.getElementById('debug-parsed-power'),
    debugUsedOffset: document.getElementById('debug-used-offset'),
    powerOffsetInput: document.getElementById('power-offset-input'),
    toggleDebugBtn: document.getElementById('toggle-debug-btn'),
    elapsedTimeDisplay: document.getElementById('elapsed-time-display'),
};
